### ISSUE TITLE
Terdapat masalah di UI dan UX

### ISSUE THREAD

**Issue by Ariska138** [ADaneshS1/portal-siswa-by-danesh-revamp-#1]
- [x] sebaiknya ketika belum login, diarahkan ke halaman login. karena halaman login lebih besar digunakan (bisa jadi tiap hari dikunjungi) daripada halaman daftar (hanya sekali)

- [x] (optional) tampilan tidak support dart mode.
- [x] tombol login pada halaman registration masuk ke halaman registration

**Comment by ADaneshS1** [comment]
Selesai

**Comment by Ariska138** [comment]
sudah diperbaiki @Ariska138 
![demo1](https://github.com/ADaneshS1/portal-siswa-by-danesh-revamp-/assets/1137972/1ac45eb0-6c53-4a94-9373-caa9416d5124)

**Comment by ADaneshS1** [comment]
![Uploading afterwork.gif…]()

**Comment by ADaneshS1** [comment]
![afterwork](https://github.com/ADaneshS1/portal-siswa-by-danesh-revamp-/assets/114051600/0fb40de6-513f-44b8-a47a-21f658a5a120)
