### ISSUE TITLE
bug ui: pada feature list users (feature buat admin) seharusnya tidak muncul tabelnya ketika dibuka sebagai siswa

### ISSUE THREAD

**Issue by Ariska138** [ADaneshS1/portal-siswa-by-danesh-revamp-#4]
- [x]  ketika login sebagai siswa, masih terdapat table users yg diperuntukkan untuk admin. walaupun tidak ada datanya.

**Comment by ADaneshS1** [comment]
![test](https://github.com/ADaneshS1/portal-siswa-by-danesh-revamp-/assets/114051600/ef45b98e-0455-4307-a256-67eee83dcade)

**Comment by ADaneshS1** [comment]
@Ariska138

**Comment by Ariska138** [comment]
sip
